llm:
  provider: "openai"
  clients:
    fireworksai:
      _target_: llm_chatbot_api.core.fireworksai.FireworksLLM
      model_name: "accounts/fireworks/models/llama-v3-70b-instruct"
      system_prompt: "You are helpful an AI assistant."
      chat_history_limit: 10
      max_tokens: 2500
      temperature: 0.7
    openai:
      _target_: llm_chatbot_api.core.openai.OpenAI
      model_name: "gpt-4o-mini"
      prompt_template: "You are helpful an AI assistant."
      chat_history_limit: 10
      max_tokens: 2500
      temperature: 0.7
api:
    version: "0.1.0"
    title: "LLM Chatbot API"
    description: "API for interaction with llm chatbot"
    host: "0.0.0.0"
    port: 8000